// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminAdd: typeof import('./src/components/super/admin/AdminAdd.vue')['default']
    Application: typeof import('./src/components/visitor/introduce/Application.vue')['default']
    Apply: typeof import('./src/components/visitor/application/Apply.vue')['default']
    Aside: typeof import('./src/components/admin/Aside.vue')['default']
    AsyncList: typeof import('./src/components/admin/task/AsyncList.vue')['default']
    Db: typeof import('./src/components/user/application/Db.vue')['default']
    DbList: typeof import('./src/components/admin/application/DbList.vue')['default']
    DbPull: typeof import('./src/components/admin/image/DbPull.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ErrorList: typeof import('./src/components/super/error/ErrorList.vue')['default']
    ForgetPassword: typeof import('./src/components/common/ForgetPassword.vue')['default']
    Function: typeof import('./src/components/visitor/introduce/Function.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    Index: typeof import('./src/components/admin/Index.vue')['default']
    Linux: typeof import('./src/components/user/application/Linux.vue')['default']
    LinuxList: typeof import('./src/components/admin/application/LinuxList.vue')['default']
    LinuxPull: typeof import('./src/components/admin/image/LinuxPull.vue')['default']
    Login: typeof import('./src/components/common/Login.vue')['default']
    Register: typeof import('./src/components/common/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/visitor/introduce/User.vue')['default']
    UserList: typeof import('./src/components/admin/application/UserList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
